defmodule TemporaryHack.UserIdentities.UserIdentity do
  @moduledoc """
  Generated by pow_assent.
  """
  use Ecto.Schema
  use PowAssent.Ecto.UserIdentities.Schema, user: TemporaryHack.Users.User

  schema "user_identities" do
    pow_assent_user_identity_fields()

    timestamps()
  end
end
