name: 'main'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

on:
  push:
    branches: [ main ]

jobs:
  test:
    uses: ./.github/workflows/test.yml
  deploy:
    name: Deploy 
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
    
